 export default interface category {    
    entities:[{
        id:number;
        title:string;
        description:string;
        password:string;
        repassword:string;
        },
        {
        id:number;
        title:string;
        description:string;
        password:string;
        repassword:string;
        },
        {
        id:number;
        title:string;
        description:string;
        password:string;
        repassword:string;
        },
        {
        id:number;
        title:string;
        description:string;
        password:string;
        repassword:string;
        },
        {
        id:number;
        title:string;
        description:string;
        password:string;
        repassword:string;
        },
        {
        id:number;
        title:string;
        description:string;
        password:string;
        repassword:string;
        },
        ]
  
}
